### ISSUE TITLE
剪枝后模型仅参数量减少，但推理速度没有变快，甚至还比没剪枝的模型要慢一点点

### ISSUE THREAD

**Issue by yao-zheng-yi** [ZJU-lishuang/yolov5_prune#17]
@ZJU-lishuang 你好，请教一个问题
我在step3进行剪枝的时候，除了readme里的剪枝策略一，其他剪枝方法都有使用过，我最开始使用八倍通道剪枝，运行slim_prune_yolov5s_8x.py，进行微调之后，模型的大小减少了，但推理时间并没有减少，甚至比没有剪枝的模型还要慢上一点点。之后我尝试了除了策略一的所有剪枝方案对稀疏化训练后得到的模型进行剪枝，但剪枝后的模型只是参数量有减少，而推理时间几乎没变化，想请教一下是什么原因。
是我稀疏化训练有问题？还是剪枝策略有问题？

下面是step2稀疏化训练的可视化结果

![map](https://user-images.githubusercontent.com/41265163/109417650-76b31000-79ff-11eb-8137-e5238e2b7f23.png)
![bn](https://user-images.githubusercontent.com/41265163/109417656-7d418780-79ff-11eb-9288-4fab19dde1b5.png)

下面是我尝试的每一种剪枝策略的运行结果和参数设置

剪枝策略三，八倍通道剪枝，运行slim_prune_yolov5s_8x.py

![slim_8x_opt](https://user-images.githubusercontent.com/41265163/109417722-c42f7d00-79ff-11eb-884c-a7ff7b8275ed.png)
![slim_8x](https://user-images.githubusercontent.com/41265163/109417725-ca255e00-79ff-11eb-9b87-5161d83c86f5.png)

剪枝策略三，运行slim_prune_yolov5s.py

![slim_opt](https://user-images.githubusercontent.com/41265163/109417753-e1fce200-79ff-11eb-894a-4aebab70d9f7.png)
![slim](https://user-images.githubusercontent.com/41265163/109417761-e88b5980-79ff-11eb-81c8-c6e88437d00a.png)

剪枝策略四，层剪枝，运行layer_prune_yolov5s.py

![layer_opt](https://user-images.githubusercontent.com/41265163/109417797-0ce73600-7a00-11eb-8714-4639a61ec43e.png)
![layer](https://user-images.githubusercontent.com/41265163/109417801-12448080-7a00-11eb-8037-7bb9c41548f2.png)

剪枝策略二，对shortcut层也进行剪枝，运行shortcut_prune_yolov5s.py 

![shortut_opt](https://user-images.githubusercontent.com/41265163/109417827-2f794f00-7a00-11eb-9206-5593151aba85.png)
![shortut](https://user-images.githubusercontent.com/41265163/109417832-343e0300-7a00-11eb-8051-14d9b2bcc623.png)

**Comment by ZJU-lishuang** [comment]
瓶颈在网络深度上，剪枝只是减少了网络参数，没有改变深度 Shuang Li 邮箱qqlishuang@gmail.com 签名由 网易邮箱大师 定制 在2021年03月01日 10:02，yao-zheng-yi 写道： @ZJU-lishuang 你好，请教一个问题 我在step3进行剪枝的时候，除了readme里的剪枝策略一，其他剪枝方法都有使用过，我最开始使用八倍通道剪枝，运行slim_prune_yolov5s_8x.py，进行微调之后，模型的大小减少了，但推理时间并没有减少，甚至比没有剪枝的模型还要慢上一点点。之后我尝试了除了策略一的所有剪枝方案对稀疏化训练后得到的模型进行剪枝，但剪枝后的模型只是参数量有减少，而推理时间几乎没变化，想请教一下是什么原因。 是我稀疏化训练有问题？还是剪枝策略有问题？ 下面是step2稀疏化训练的可视化结果 下面是我尝试的每一种剪枝策略的运行结果和参数设置 剪枝策略三，八倍通道剪枝，运行slim_prune_yolov5s_8x.py 剪枝策略三，运行slim_prune_yolov5s.py 剪枝策略四，层剪枝，运行layer_prune_yolov5s.py 剪枝策略二，对shortcut层也进行剪枝，运行shortcut_prune_yolov5s.py — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yao-zheng-yi** [comment]
> 瓶颈在网络深度上，剪枝只是减少了网络参数，没有改变深度 Shuang Li 邮箱qqlishuang@gmail.com 签名由 网易邮箱大师 定制 在2021年03月01日 10:02，yao-zheng-yi 写道： @ZJU-lishuang 你好，请教一个问题 我在step3进行剪枝的时候，除了readme里的剪枝策略一，其他剪枝方法都有使用过，我最开始使用八倍通道剪枝，运行slim_prune_yolov5s_8x.py，进行微调之后，模型的大小减少了，但推理时间并没有减少，甚至比没有剪枝的模型还要慢上一点点。之后我尝试了除了策略一的所有剪枝方案对稀疏化训练后得到的模型进行剪枝，但剪枝后的模型只是参数量有减少，而推理时间几乎没变化，想请教一下是什么原因。 是我稀疏化训练有问题？还是剪枝策略有问题？ 下面是step2稀疏化训练的可视化结果 下面是我尝试的每一种剪枝策略的运行结果和参数设置 剪枝策略三，八倍通道剪枝，运行slim_prune_yolov5s_8x.py 剪枝策略三，运行slim_prune_yolov5s.py 剪枝策略四，层剪枝，运行layer_prune_yolov5s.py 剪枝策略二，对shortcut层也进行剪枝，运行shortcut_prune_yolov5s.py — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢
