### ISSUE TITLE
如何参考yolov5s.cfg得到yolov5x.cfg

### ISSUE THREAD

**Issue by yao-zheng-yi** [ZJU-lishuang/yolov5_prune#18]
@ZJU-lishuang 你好，yolov5s.yaml和yolov5x.yaml只有width_multiple和depth_multiple两个参数不一样
如果要得到yolov5x.cfg对yolov5x进行剪枝，在yolov5s.cfg的基础上如何修改可以得到yolov5x.cfg？
刚接触这方面的大小不知道该如何入手

**Comment by ZJU-lishuang** [comment]
对照yaml的网络结构，使用cfg手工搭建网络 Shuang Li 邮箱qqlishuang@gmail.com 签名由 网易邮箱大师 定制 在2021年03月03日 20:36，yao-zheng-yi 写道： @ZJU-lishuang 你好，yolov5s.yaml和yolov5x.yaml只有width_multiple和depth_multiple两个参数不一样 如果要得到yolov5x.cfg对yolov5x进行剪枝，在yolov5s.cfg的基础上如何修改可以得到yolov5x.cfg？ 刚接触这方面的大小不知道该如何入手 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yao-zheng-yi** [comment]
> 对照yaml的网络结构，使用cfg手工搭建网络 Shuang Li 邮箱qqlishuang@gmail.com 签名由 网易邮箱大师 定制 在2021年03月03日 20:36，yao-zheng-yi 写道： @ZJU-lishuang 你好，yolov5s.yaml和yolov5x.yaml只有width_multiple和depth_multiple两个参数不一样 如果要得到yolov5x.cfg对yolov5x进行剪枝，在yolov5s.cfg的基础上如何修改可以得到yolov5x.cfg？ 刚接触这方面的大小不知道该如何入手 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

我使用netron可视化yolov5s.pt的网络结构，但是和已有的yolov5s.cfg结构完全不同，不知道该如何手工搭建
请问有相关的博客或者教程吗？还是不大明白该怎么改，v5x和v5s的yaml仅有两个参数不同，网络结构是一样的吗？

**Comment by ZJU-lishuang** [comment]
结构相似，但不同，cfg的搭建是一层一层搭建的，并不能简单套用，可以转成onnx格式查看结构 Shuang Li 邮箱qqlishuang@gmail.com 签名由 网易邮箱大师 定制 在2021年03月03日 21:25，yao-zheng-yi 写道： 对照yaml的网络结构，使用cfg手工搭建网络 Shuang Li 邮箱qqlishuang@gmail.com 签名由 网易邮箱大师 定制 在2021年03月03日 20:36，yao-zheng-yi 写道： @ZJU-lishuang 你好，yolov5s.yaml和yolov5x.yaml只有width_multiple和depth_multiple两个参数不一样 如果要得到yolov5x.cfg对yolov5x进行剪枝，在yolov5s.cfg的基础上如何修改可以得到yolov5x.cfg？ 刚接触这方面的大小不知道该如何入手 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. 我使用netron可视化yolov5s.pt的网络结构，但是和已有的yolov5s.cfg结构完全不同，不知道该如何手工搭建 请问有相关的博客或者教程吗？还是不大明白该怎么改，v5x和v5s的yaml仅有两个参数不同，网络结构是一样的吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yao-zheng-yi** [comment]
要对yolov5x做剪枝的话，除了搭建yolov5x.cfg文件，剪枝策略中的copy_weights函数需要重写吗？比如要使用slim_prune_yolov5s_8x.py进行剪枝，里面的copy_weights_v4函数可以直接用还是需要再进行修改？

**Comment by ZJU-lishuang** [comment]
copy_weights_v4要改，yolov5x是yolov5s变化是某些层翻倍，通道数增加，改起来应该很快的

**Comment by yao-zheng-yi** [comment]
我现在想先理解对yolov5s剪枝的时候copy_weights_v4函数是怎么进行复制的，但是看的不是很明白，我结合yolov5s.cfg的网络结构图来看，但没看懂它是如何把model进行复制的，有没有方法能够帮助理解？

focus = list(modelyolov5.model.children())[0]
    copy_conv(focus.conv, model.module_list[1])
    conv1 = list(modelyolov5.model.children())[1]
    copy_conv(conv1, model.module_list[2])
    cspnet1 = list(modelyolov5.model.children())[2]
    copy_conv(cspnet1.cv2, model.module_list[3])
    copy_conv(cspnet1.cv1, model.module_list[5])
    copy_conv(cspnet1.m[0].cv1, model.module_list[6])
    copy_conv(cspnet1.m[0].cv2, model.module_list[7])
    copy_conv(cspnet1.cv3, model.module_list[10])
    conv2 = list(modelyolov5.model.children())[3]

比如上面这部分代码，list(modelyolov5.model.children())[x]和model.module_list[x]，每个下标x是如何确定并两两对应使用copy_conv函数进行复制的？
有什么方法能够直观地理解它们的结构并修改代码吗？

**Comment by ZJU-lishuang** [comment]
将模型转为onnx格式，使用Netron看网络结构，和cfg对照来看，cfg也可以使用Netron看网络结构

**Comment by yao-zheng-yi** [comment]
我已经使用了netron查看网络结构，可以看明白yolov5.pt的网络结构如何转换为yolov5.cfg
但是我通过网络结构没看明白这个函数，就比如看不懂cspnet1.cv2为什么是复制给model.module_list[3]而不是model.module_list[4]，没搞明白这些的对应关系

**Comment by ZJU-lishuang** [comment]
两种方式都能转为网络结构图来看，结构应该是差不多一样的。你先从输入图片开始看，一层一层往下去一一对应。

**Comment by yao-zheng-yi** [comment]
感谢回复，我直接输出了modelyolov5和model的网络结构，这两天已经能大概看明白modelyolov5.model.children和modelmodule_list的对应关系了

**Comment by ZJU-lishuang** [comment]
yolov5的基础结构已经有了，从s到x就是一个扩充的过程，基本上复制粘贴加改网络通道数就出来了。
改好以后用[test_yolov5s](https://github.com/ZJU-lishuang/yolov5_prune/blob/v4/test_yolov5s.py)这个对比一下输出就可以了

**Comment by yao-zheng-yi** [comment]
好的，我在写cfg文件的时候遇到一个问题
[convolutional]
batch_normalize=1
filters=32
size=1
stride=1
pad=1
activation=SiLU

size，stride，pad这三个参数的值应该是按netron里面显示的参数来设置的吧
但是netron里面有的卷积pad的值是0，而在yolov5s.cfg里面，所有卷积的pad都是1
这是你当时写错了，还是说size，stride，pad这三个参数的值并不是按netron里面的值来设置的
![Snipaste_2021-03-09_12-07-36](https://user-images.githubusercontent.com/41265163/110417397-818d3500-80d0-11eb-92bd-85f3b7131c6c.png)

**Comment by ZJU-lishuang** [comment]
cfg中卷积的pad在代码里面计算如下
```python
pad = (kernel_size - 1) // 2 if int(mdef['pad']) else 0
```
并没有直接使用pad的值

**Comment by yao-zheng-yi** [comment]
多谢
这样计算的话size=1的时候，pad的 值不是应该为0吗？为什么还是1？
那filter，size和stride是怎么计算的？

**Comment by ZJU-lishuang** [comment]
size=1时，pad是0呀，你debug代码就知道了。
cfg层的计算在modelori.py文件里面，create_modules函数

**Comment by yao-zheng-yi** [comment]
但是在你的yolov5-v4这个项目的yolov5s_v4.cfg里面，所有的卷积pad都是1，size=1和size=3的卷积，pad都是1
所以我才会奇怪，是你写错了吗？

**Comment by ZJU-lishuang** [comment]
你可以调试一下test_yolov5s.py这个文件，里面输出两种模型对同一张图的检测，是相同的结果。你要看代码里面是怎么写的。我是沿用了别人之前的写法。

**Comment by yao-zheng-yi** [comment]
yolov5x.cfg文件里，yolo层的anchors和class根据自己的数据集修改，jitter后面的那些参数的值和yolov5s.cfg里的是一样的吗？
[yolo]
mask = 0,1,2
anchors = 40, 39,  51, 50,  61, 59, 75, 69, 62, 92, 88, 98, 115, 77, 93, 129, 128, 115
classes=2
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
scale_x_y = 1.2
iou_thresh=0.213
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
nms_kind=greedynms
beta_nms=0.6

**Comment by ZJU-lishuang** [comment]
只需要改anchor和class，前面一层卷积层数也要改，参考yolov4改动类别数的做法。后面是训练的参数，这里我没用cfg那一套训练，所以应该是没用的。

**Comment by ZJU-lishuang** [comment]
只需要改anchor和class，前面一层卷积层数也要改，参考yolov4改动类别数的做法。后面是训练的参数，这里我没用cfg那一套训练，所以应该是没用的。
