### ISSUE TITLE
剪枝

### ISSUE THREAD

**Issue by ChengJiayaqi** [ZJU-lishuang/yolov5_prune#54]
楼主，请问weights及其文件夹下的pt文件在哪？（剪枝用）

**Comment by ZJU-lishuang** [comment]
fitst,you should learn about [yolov5](https://github.com/ultralytics/yolov5).
And then,you can download the weights from the [pretrained checkpoints](https://github.com/ultralytics/yolov5#pretrained-checkpoints)

**Comment by 123wujiao** [comment]
博主，我在运行第三步剪枝的时候出现
Traceback (most recent call last):
  File "prune_yolov5s.py", line 379, in <module>
    percent_limit = (sorted_bn==highest_thre).nonzero().item()/len(bn_weights)
ValueError: only one element tensors can be converted to Python scalars

**Comment by ZJU-lishuang** [comment]
稀疏不到位 在2021年09月18日 17:42，123wujiao 写道： 博主，我在运行第三步剪枝的时候出现 Traceback (most recent call last): File "prune_yolov5s.py", line 379, in percent_limit = (sorted_bn==highest_thre).nonzero().item()/len(bn_weights) ValueError: only one element tensors can be converted to Python scalars — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
